const websiteIntegration = { id: 'website', label: 'Website profile', required: true, reason: 'Brand, audience, offer, and voice context' };

const platformIntegration = (id, label, reason = 'Optional publishing after approval') => ({
  id, label, required: false, reason,
});

const text = (id, label, required = true, placeholder = '', profileFallback) => ({
  id, label, type: 'text', required, placeholder, ...(profileFallback ? { profileFallback } : {}),
});

const textarea = (id, label, required = true, placeholder = '', profileFallback) => ({
  id, label, type: 'textarea', required, placeholder, ...(profileFallback ? { profileFallback } : {}),
});

const url = (id, label, required = true, placeholder = 'https://example.com') => ({
  id, label, type: 'url', required, placeholder,
});

const select = (id, label, options, required = true) => ({
  id, label, type: 'select', required, options,
});

const defineWorkflow = ({
  integrations = [], fields, ...workflow
}) => ({
  ...workflow,
  integrations: [websiteIntegration, ...integrations],
  fields,
});

export const WORKFLOW_CATALOG = [
  defineWorkflow({
    id: 'assistant.email.draft',
    title: 'Draft a business email',
    shortTitle: 'Business email',
    eyebrow: 'Move work forward',
    description: 'Turn context and an objective into a concise, credible email ready for review.',
    outcome: 'A subject line and polished email draft with a clear next step.',
    icon: '@',
    accent: '#c084fc',
    integrations: [platformIntegration('gmail', 'Gmail')],
    fields: [
      textarea('context', 'What is the email about?', true, 'Share the situation, relationship, and relevant facts'),
      text('recipient', 'Who is receiving it?', true, 'e.g. A prospect, client, partner, or teammate'),
      text('goal', 'What should happen next?', true, 'e.g. Confirm a meeting or approve a proposal'),
      select('tone', 'Preferred tone', ['Direct and professional', 'Warm and helpful', 'Concise and executive']),
    ],
    estimate: '2–4 minutes',
    outputType: 'Email draft',
  }),
  defineWorkflow({
    id: 'assistant.meeting.brief',
    title: 'Prepare a meeting brief',
    shortTitle: 'Meeting brief',
    eyebrow: 'Enter prepared',
    description: 'Build an agenda, talking points, questions, and desired decisions from your context.',
    outcome: 'A focused meeting brief with agenda, questions, risks, and desired outcomes.',
    icon: '✓',
    accent: '#a78bfa',
    integrations: [platformIntegration('googlecalendar', 'Google Calendar', 'Optional meeting context')],
    fields: [
      text('meeting', 'What is the meeting?', true, 'e.g. Discovery call with a manufacturing prospect'),
      text('attendees', 'Who will attend?', true, 'Names, roles, or organizations'),
      textarea('context', 'What context should Promarkia know?', true, 'Goals, history, constraints, and open questions'),
      text('decision', 'What decision or next step do you want?', true, 'The ideal meeting outcome'),
    ],
    estimate: '3–5 minutes',
    outputType: 'Meeting brief',
  }),
  defineWorkflow({
    id: 'assistant.weekly.plan',
    title: 'Build a weekly marketing plan',
    shortTitle: 'Weekly plan',
    eyebrow: 'Protect your focus',
    description: 'Convert priorities and constraints into a practical, sequenced marketing work plan.',
    outcome: 'A prioritized one-week plan with owners, milestones, dependencies, and success checks.',
    icon: '7d',
    accent: '#8b5cf6',
    fields: [
      textarea('priorities', 'What must move this week?', true, 'List the most important marketing outcomes'),
      text('capacity', 'Who is available and for how long?', true, 'People, hours, and important constraints'),
      textarea('commitments', 'What is already committed?', false, 'Meetings, launches, reviews, or deadlines'),
      select('format', 'Plan format', ['Daily schedule', 'Priority backlog', 'Owner-by-owner plan']),
    ],
    estimate: '3–5 minutes',
    outputType: 'Weekly action plan',
  }),

  defineWorkflow({
    id: 'image.social.create',
    title: 'Create a social graphic',
    shortTitle: 'Social graphic',
    eyebrow: 'Stop the scroll',
    description: 'Develop an on-brand visual concept and production-ready image for a social post.',
    outcome: 'A finished social graphic plus alt text and platform-safe copy guidance.',
    icon: '▧',
    accent: '#f472b6',
    fields: [
      text('message', 'What is the one message?', true, 'The idea viewers should understand immediately'),
      select('format', 'Target format', ['LinkedIn landscape', 'Instagram square', 'Instagram portrait', 'X landscape']),
      textarea('visual', 'Visual direction', false, 'Subject, setting, metaphor, or reference style'),
      text('cta', 'Optional call to action', false, 'Keep it short'),
    ],
    estimate: '4–7 minutes',
    outputType: 'Social image',
  }),
  defineWorkflow({
    id: 'image.blog.cover',
    title: 'Create a blog cover image',
    shortTitle: 'Blog cover',
    eyebrow: 'Package the idea',
    description: 'Translate an article premise into a strong editorial cover visual without text clutter.',
    outcome: 'A publication-ready cover image with alt text and a reusable image brief.',
    icon: '▤',
    accent: '#fb7185',
    fields: [
      text('articleTitle', 'Article title', true, 'The working or final title'),
      textarea('summary', 'What is the article really saying?', true, 'The central argument or takeaway'),
      select('style', 'Visual style', ['Editorial photography', 'Technical illustration', 'Abstract concept', 'Product-led']),
      select('aspectRatio', 'Aspect ratio', ['16:9', '3:2', '1:1']),
    ],
    estimate: '4–7 minutes',
    outputType: 'Cover image',
  }),
  defineWorkflow({
    id: 'image.infographic.create',
    title: 'Create an infographic',
    shortTitle: 'Infographic',
    eyebrow: 'Make complexity clear',
    description: 'Turn a process, comparison, or dataset into a structured, easy-to-scan visual.',
    outcome: 'An infographic concept, verified copy hierarchy, and finished visual.',
    icon: '▥',
    accent: '#f59e0b',
    fields: [
      textarea('content', 'What should the infographic explain?', true, 'Include the facts, steps, or comparison points'),
      text('audience', 'Who needs to understand it?', true, '', 'audience'),
      select('layout', 'Preferred layout', ['Process flow', 'Comparison', 'Timeline', 'Data snapshot']),
      text('source', 'Evidence or source URL', false, 'Optional source for factual claims'),
    ],
    estimate: '6–10 minutes',
    outputType: 'Infographic',
  }),
  defineWorkflow({
    id: 'image.ad.variants',
    title: 'Create ad image variants',
    shortTitle: 'Ad visuals',
    eyebrow: 'Test the angle',
    description: 'Create distinct visual directions around one offer for structured creative testing.',
    outcome: 'Three differentiated ad-image concepts and production-ready variants.',
    icon: 'A/B',
    accent: '#f97316',
    fields: [
      text('offer', 'What are you promoting?', true, '', 'offer'),
      text('audience', 'Who should act?', true, '', 'audience'),
      text('benefit', 'What is the strongest benefit?', true, 'A specific outcome or avoided pain'),
      select('platform', 'Ad platform', ['LinkedIn', 'Meta', 'Google Display', 'TikTok']),
    ],
    estimate: '6–10 minutes',
    outputType: 'Ad image set',
  }),

  defineWorkflow({
    id: 'video.faceless.explainer',
    title: 'Create a faceless explainer',
    shortTitle: 'Faceless explainer',
    eyebrow: 'Teach something useful',
    description: 'Build a narrated, evidence-led explainer using diagrams, product footage, captions, and generated b-roll.',
    outcome: 'A finished faceless explainer with script, narration, captions, visuals, and verified final MP4.',
    icon: '▶',
    accent: '#ef4444',
    integrations: [platformIntegration('youtube', 'YouTube'), platformIntegration('tiktok', 'TikTok')],
    fields: [
      textarea('lesson', 'What should viewers understand?', true, 'Teach a useful mechanism, framework, or practical decision'),
      text('audience', 'Who is this for?', true, '', 'audience'),
      textarea('example', 'What example should make it concrete?', true, 'A recognizable business situation, workflow, or decision'),
      text('takeaway', 'What should viewers remember at the end?', true, 'One concise practical insight'),
      select('length', 'Target length', ['30–45 seconds', '60–90 seconds', '3–5 minutes', '6–10 minutes']),
      select('format', 'Primary format', ['9:16 vertical', '16:9 landscape', 'Both']),
      select('visualStyle', 'Visual style', ['Clean business motion graphics', 'Hand-drawn explainer', 'Bold kinetic typography', 'Cinematic documentary']),
      select('productionMode', 'Production approach', ['Auto', 'Motion graphics', 'Hybrid', 'Cinematic']),
      select('platform', 'Primary destination', ['LinkedIn / Instagram / TikTok', 'YouTube', 'Website / presentation']),
      select('costCeiling', 'Paid-generation policy', ['No automatic paid regenerations', 'Motion graphics only — no paid footage', 'Allow up to 3 Veo clips', 'Allow up to 6 Veo clips']),
    ],
    estimate: '10–25 minutes',
    outputType: 'Explainer video',
  }),
  defineWorkflow({
    id: 'video.product.demo',
    title: 'Create a product demo video',
    shortTitle: 'Product demo',
    eyebrow: 'Show real proof',
    description: 'Turn real product footage into a tight story with callouts, narration, and a clear use case.',
    outcome: 'A polished product demo built around real UI evidence and a specific viewer problem.',
    icon: 'UI',
    accent: '#f87171',
    integrations: [platformIntegration('youtube', 'YouTube'), platformIntegration('tiktok', 'TikTok')],
    fields: [
      textarea('workflow', 'What product workflow should the video show?', true, 'Describe the input, actions, and output'),
      url('footage', 'Product footage or public demo URL', true),
      text('viewerProblem', 'What problem does this solve?', true, 'Use the viewer’s language'),
      select('format', 'Primary format', ['9:16 vertical', '16:9 landscape', 'Both']),
    ],
    estimate: '12–25 minutes',
    outputType: 'Product demo video',
  }),
  defineWorkflow({
    id: 'video.youtube.longform',
    title: 'Create a YouTube video',
    shortTitle: 'YouTube video',
    eyebrow: 'Own the topic',
    description: 'Develop a useful long-form video that earns trust through depth, examples, and visual evidence.',
    outcome: 'A finished 16:9 YouTube video plus title, description, chapters, thumbnail brief, and upload package.',
    icon: 'YT',
    accent: '#dc2626',
    integrations: [platformIntegration('youtube', 'YouTube')],
    fields: [
      textarea('topic', 'What topic should this video own?', true, 'Focus on a buyer-relevant question you can answer deeply'),
      text('audience', 'Who is searching for this?', true, '', 'audience'),
      select('length', 'Target length', ['5–8 minutes', '8–12 minutes', '12–20 minutes']),
      textarea('evidence', 'Examples, sources, or product proof', false, 'Add URLs, facts, screenshots, or demonstrations to include'),
    ],
    estimate: '20–40 minutes',
    outputType: 'YouTube video package',
  }),
  defineWorkflow({
    id: 'video.tiktok.short',
    title: 'Create a TikTok video',
    shortTitle: 'TikTok video',
    eyebrow: 'Earn attention fast',
    description: 'Create a concise vertical lesson with an immediate hook, visual proof, and native pacing.',
    outcome: 'A captioned 9:16 TikTok video with hook variants, caption, and publishing metadata.',
    icon: '♪',
    accent: '#22d3ee',
    integrations: [platformIntegration('tiktok', 'TikTok')],
    fields: [
      text('lesson', 'What is the useful takeaway?', true, 'One clear, specific lesson'),
      text('audience', 'Who needs this?', true, '', 'audience'),
      select('length', 'Target length', ['15–25 seconds', '25–45 seconds', '45–60 seconds']),
      textarea('proof', 'What proof or example can we show?', false, 'Product footage, diagram, statistic, or concrete scenario'),
    ],
    estimate: '8–18 minutes',
    outputType: 'TikTok video',
  }),
  defineWorkflow({
    id: 'video.shorts.cutdown',
    title: 'Turn a video into Shorts',
    shortTitle: 'Shorts cutdowns',
    eyebrow: 'Multiply the asset',
    description: 'Find the strongest moments in a long video and package them as standalone vertical lessons.',
    outcome: 'Three coherent vertical cutdowns with captions, hooks, and platform-ready metadata.',
    icon: '×3',
    accent: '#fb7185',
    integrations: [platformIntegration('youtube', 'YouTube'), platformIntegration('tiktok', 'TikTok')],
    fields: [
      url('source', 'Source video URL', true),
      text('audience', 'Who should these clips reach?', true, '', 'audience'),
      select('count', 'Number of cutdowns', ['3 clips', '5 clips', '8 clips']),
      select('length', 'Target clip length', ['20–35 seconds', '35–60 seconds', '60–90 seconds']),
    ],
    estimate: '10–20 minutes',
    outputType: 'Vertical video pack',
  }),
  defineWorkflow({
    id: 'video.captions.add',
    title: 'Add captions and callouts',
    shortTitle: 'Captions & callouts',
    eyebrow: 'Improve retention',
    description: 'Transcribe a video and add readable, timed captions plus selective visual emphasis.',
    outcome: 'A captioned MP4 plus transcript and subtitle file.',
    icon: 'CC',
    accent: '#fbbf24',
    fields: [
      url('source', 'Video URL', true),
      select('captionStyle', 'Caption style', ['Clean professional', 'Kinetic emphasis', 'Minimal subtitles']),
      select('format', 'Output format', ['Keep source format', '9:16 vertical', '16:9 landscape']),
      text('terms', 'Terms that must be spelled correctly', false, 'Brand names, product names, acronyms, or people'),
    ],
    estimate: '6–12 minutes',
    outputType: 'Captioned video',
  }),
  defineWorkflow({
    id: 'video.reframe.platforms',
    title: 'Reframe a video for every platform',
    shortTitle: 'Video reframing',
    eyebrow: 'Fit every feed',
    description: 'Create platform-safe crops while preserving the subject, captions, and important UI.',
    outcome: 'Validated 16:9, 9:16, and 1:1 variants from one source video.',
    icon: '↔',
    accent: '#38bdf8',
    fields: [
      url('source', 'Source video URL', true),
      text('focus', 'What must stay in frame?', true, 'Product UI, speaker, object, or text region'),
      select('outputs', 'Required outputs', ['16:9 + 9:16', '16:9 + 9:16 + 1:1', '9:16 only']),
      select('captionHandling', 'Caption handling', ['Preserve existing captions', 'Regenerate captions', 'No captions']),
    ],
    estimate: '6–12 minutes',
    outputType: 'Multi-format video set',
  }),
  defineWorkflow({
    id: 'video.localize',
    title: 'Localize a video',
    shortTitle: 'Video localization',
    eyebrow: 'Reach another market',
    description: 'Adapt narration, captions, and on-screen copy while preserving meaning and brand tone.',
    outcome: 'Localized video variants with translated transcript, captions, and terminology checks.',
    icon: '文',
    accent: '#34d399',
    fields: [
      url('source', 'Source video URL', true),
      text('languages', 'Target languages', true, 'e.g. French and Spanish'),
      text('terms', 'Terms that must remain unchanged', false, 'Brand, product, legal, or technical terms'),
      select('voice', 'Voice treatment', ['Localized AI narration', 'Captions only', 'Preserve original voice where possible']),
    ],
    estimate: '10–20 minutes',
    outputType: 'Localized video set',
  }),
  defineWorkflow({
    id: 'video.virality.review',
    title: 'Analyze a video hook',
    shortTitle: 'Video hook review',
    eyebrow: 'Strengthen retention',
    description: 'Evaluate the opening, pacing, clarity, and likely retention leaks before publishing.',
    outcome: 'An evidence-based hook and retention review with concrete edits to improve clarity, pacing, and completion.',
    icon: '⚡',
    accent: '#facc15',
    fields: [
      url('source', 'Video URL', true),
      text('audience', 'Who is the intended viewer?', true, '', 'audience'),
      text('goal', 'What should the viewer do or remember?', true, 'The intended outcome'),
      select('platform', 'Primary platform', ['TikTok', 'YouTube Shorts', 'YouTube', 'LinkedIn']),
    ],
    estimate: '4–8 minutes',
    outputType: 'Video performance review',
  }),

  defineWorkflow({
    id: 'social.linkedin.create',
    title: 'Create a LinkedIn post',
    shortTitle: 'LinkedIn post',
    eyebrow: 'Start a conversation',
    description: 'Shape one useful idea into a credible post with a strong hook and natural call to action.',
    outcome: 'Three hook options and one polished LinkedIn draft for approval.',
    icon: 'in',
    accent: '#38bdf8',
    integrations: [platformIntegration('linkedin', 'LinkedIn')],
    fields: [
      textarea('idea', 'What idea or story do you want to share?', true, 'A lesson, opinion, result, or useful observation'),
      text('audience', 'Who should care about this?', true, '', 'audience'),
      select('tone', 'How should it sound?', ['Direct and practical', 'Thoughtful and personal', 'Bold and contrarian', 'Educational']),
      text('cta', 'Desired response', false, 'Optional — comment, follow, visit, or book'),
    ],
    estimate: '2–4 minutes',
    outputType: 'LinkedIn draft',
  }),
  defineWorkflow({
    id: 'social.reddit.create',
    title: 'Create a Reddit post',
    shortTitle: 'Reddit post',
    eyebrow: 'Earn useful feedback',
    description: 'Draft a community-native post that leads with value instead of promotion.',
    outcome: 'A subreddit-aware title and post draft with a promotional-risk check.',
    icon: 'r/',
    accent: '#fb7185',
    integrations: [platformIntegration('reddit', 'Reddit')],
    fields: [
      text('subreddit', 'Which subreddit is this for?', true, 'e.g. r/smallbusiness'),
      textarea('topic', 'What do you want to discuss?', true, 'Lead with a useful question, lesson, or resource'),
      text('value', 'What value will the community get?', true, 'A tested checklist or useful explanation'),
      text('disclosure', 'Any affiliation to disclose?', false, 'Optional but recommended when relevant'),
    ],
    estimate: '3–5 minutes',
    outputType: 'Reddit draft',
  }),
  defineWorkflow({
    id: 'social.reddit.discover',
    title: 'Find Reddit conversations',
    shortTitle: 'Reddit opportunities',
    eyebrow: 'Find real demand',
    description: 'Search for high-intent conversations where a helpful, non-spammy reply would be relevant.',
    outcome: 'A ranked opportunity list and reply drafts; nothing is posted automatically.',
    icon: '⌕',
    accent: '#f59e0b',
    integrations: [platformIntegration('reddit', 'Reddit', 'Search and optional approved replies')],
    fields: [
      textarea('problem', 'What problem or buying signal should we look for?', true, 'e.g. Teams looking for help automating inbound lead follow-up'),
      text('communities', 'Preferred communities', false, 'Optional — comma-separated subreddits'),
      text('offer', 'What can you genuinely help with?', true, '', 'offer'),
      select('lookback', 'How recent should posts be?', ['Last 24 hours', 'Last 7 days', 'Last 30 days']),
    ],
    estimate: '5–8 minutes',
    outputType: 'Opportunity report',
  }),
  defineWorkflow({
    id: 'social.x.thread',
    title: 'Create an X thread',
    shortTitle: 'X thread',
    eyebrow: 'Explain the idea',
    description: 'Turn one useful point of view into a tight, logically sequenced thread.',
    outcome: 'A strong opening post and concise thread with evidence, examples, and a natural close.',
    icon: 'X',
    accent: '#94a3b8',
    integrations: [platformIntegration('twitter', 'X')],
    fields: [
      textarea('idea', 'What should the thread explain?', true, 'The central argument, lesson, or breakdown'),
      text('audience', 'Who is it for?', true, '', 'audience'),
      select('length', 'Thread length', ['5–7 posts', '8–12 posts', '12–16 posts']),
      text('source', 'Evidence or source URL', false, 'Optional supporting source'),
    ],
    estimate: '3–6 minutes',
    outputType: 'X thread draft',
  }),
  defineWorkflow({
    id: 'social.instagram.carousel',
    title: 'Create an Instagram carousel',
    shortTitle: 'Instagram carousel',
    eyebrow: 'Teach by swiping',
    description: 'Structure a useful lesson across clear, visual slides with a strong cover and conclusion.',
    outcome: 'A slide-by-slide carousel script, visual brief, caption, and alt text.',
    icon: 'IG',
    accent: '#e879f9',
    integrations: [platformIntegration('instagram', 'Instagram')],
    fields: [
      text('lesson', 'What should the carousel teach?', true, 'One practical idea or framework'),
      text('audience', 'Who is it for?', true, '', 'audience'),
      select('slides', 'Number of slides', ['6 slides', '8 slides', '10 slides']),
      text('cta', 'Final action', false, 'Save, share, comment, or visit'),
    ],
    estimate: '4–7 minutes',
    outputType: 'Carousel package',
  }),
  defineWorkflow({
    id: 'social.calendar.create',
    title: 'Build a social content calendar',
    shortTitle: 'Social calendar',
    eyebrow: 'Publish with purpose',
    description: 'Plan a balanced sequence of educational, proof-led, and conversion content.',
    outcome: 'A channel-specific calendar with topics, hooks, formats, cadence, and success measures.',
    icon: '30',
    accent: '#2dd4bf',
    fields: [
      text('goal', 'What business goal should content support?', true, 'Authority, demand, product adoption, or pipeline'),
      text('audience', 'Primary audience', true, '', 'audience'),
      text('channels', 'Which channels?', true, 'e.g. LinkedIn, YouTube, and TikTok'),
      select('horizon', 'Planning horizon', ['2 weeks', '30 days', '90 days']),
    ],
    estimate: '6–10 minutes',
    outputType: 'Content calendar',
  }),

  defineWorkflow({
    id: 'content.blog.create',
    title: 'Create a blog post',
    shortTitle: 'Blog post',
    eyebrow: 'Build authority',
    description: 'Turn a useful topic into an on-brand, search-ready article and cover-image brief.',
    outcome: 'A review-ready blog draft with title, outline, article, SEO fields, and image brief.',
    icon: '✦',
    accent: '#a78bfa',
    integrations: [platformIntegration('wordpress', 'WordPress')],
    fields: [
      textarea('topic', 'What should the article be about?', true, 'A useful question your audience needs answered'),
      text('audience', 'Who is this for?', true, '', 'audience'),
      text('goal', 'What should the reader do next?', true, 'The natural next step'),
      text('keywords', 'Any target keywords?', false, 'Optional — Promarkia can suggest them'),
    ],
    estimate: '4–7 minutes',
    outputType: 'Blog draft',
  }),
  defineWorkflow({
    id: 'content.landing.page',
    title: 'Write a landing page',
    shortTitle: 'Landing page',
    eyebrow: 'Clarify the offer',
    description: 'Create a focused conversion page around one audience, problem, promise, and action.',
    outcome: 'A complete landing-page draft with section order, proof needs, objections, and CTA.',
    icon: 'LP',
    accent: '#8b5cf6',
    fields: [
      text('offer', 'What is the offer?', true, '', 'offer'),
      text('audience', 'Who is the page for?', true, '', 'audience'),
      text('problem', 'What urgent problem does it solve?', true, 'Use the buyer’s language'),
      text('cta', 'Primary call to action', true, 'e.g. Book a consultation'),
    ],
    estimate: '5–9 minutes',
    outputType: 'Landing-page copy',
  }),
  defineWorkflow({
    id: 'content.newsletter',
    title: 'Create an email newsletter',
    shortTitle: 'Newsletter',
    eyebrow: 'Stay worth opening',
    description: 'Turn a useful idea or update into an engaging email that respects the reader’s time.',
    outcome: 'Subject options, preview text, newsletter body, and a clear next action.',
    icon: '✉',
    accent: '#7c3aed',
    integrations: [platformIntegration('gmail', 'Gmail')],
    fields: [
      textarea('topic', 'What is this edition about?', true, 'Lesson, analysis, update, or curated insight'),
      text('audience', 'Who receives it?', true, '', 'audience'),
      text('takeaway', 'What should readers remember?', true, 'One clear takeaway'),
      select('format', 'Newsletter format', ['Educational essay', 'Curated roundup', 'Product update', 'Founder note']),
    ],
    estimate: '4–7 minutes',
    outputType: 'Newsletter draft',
  }),
  defineWorkflow({
    id: 'content.case.study',
    title: 'Write a case study',
    shortTitle: 'Case study',
    eyebrow: 'Turn proof into trust',
    description: 'Structure verified client evidence into a credible problem, intervention, and result story.',
    outcome: 'A case-study draft with explicit evidence gaps and no unsupported performance claims.',
    icon: 'CS',
    accent: '#6d28d9',
    fields: [
      text('client', 'Client or anonymized descriptor', true, 'Use “anonymized” if approval is not available'),
      textarea('problem', 'What was the verified problem?', true, 'Observed situation and constraints'),
      textarea('work', 'What did you actually implement?', true, 'Specific systems, decisions, and work completed'),
      textarea('results', 'What results can be substantiated?', true, 'Only verified outcomes; list missing evidence openly'),
    ],
    estimate: '6–10 minutes',
    outputType: 'Case-study draft',
  }),
  defineWorkflow({
    id: 'content.repurpose',
    title: 'Repurpose existing content',
    shortTitle: 'Repurpose content',
    eyebrow: 'Get more mileage',
    description: 'Turn an article, transcript, or idea into channel-ready content without losing the core message.',
    outcome: 'A channel-specific content pack and practical reuse plan.',
    icon: '↗',
    accent: '#34d399',
    fields: [
      textarea('source', 'Paste the source content or URL', true, 'Article, transcript, notes, or public URL'),
      text('channels', 'Which channels?', true, 'e.g. LinkedIn, newsletter, YouTube, and TikTok'),
      text('message', 'What is the one message to preserve?', true, 'The idea the audience should remember'),
      select('tone', 'Preferred tone', ['Direct and practical', 'Thoughtful and personal', 'Educational']),
    ],
    estimate: '4–7 minutes',
    outputType: 'Content pack',
  }),

  defineWorkflow({
    id: 'seo.site.analyze',
    title: 'Run an SEO analysis',
    shortTitle: 'SEO analysis',
    eyebrow: 'Improve visibility',
    description: 'Audit your site for keyword, on-page, backlink, and search visibility opportunities.',
    outcome: 'A prioritized SEO report with evidence, business impact, and measurable next actions.',
    icon: 'SEO',
    accent: '#22d3ee',
    fields: [
      url('target', 'Website or page to analyze', true),
      select('scope', 'What should the analysis prioritize?', ['Full SEO analysis', 'On-page improvements', 'Keyword opportunities', 'Backlink opportunities']),
      text('market', 'Target market or location', false, 'e.g. Canada, North America, or global'),
      text('competitors', 'Known competitors', false, 'Optional names or URLs'),
    ],
    estimate: '5–8 minutes',
    outputType: 'SEO report',
  }),
  defineWorkflow({
    id: 'seo.keywords.research',
    title: 'Research keyword opportunities',
    shortTitle: 'Keyword research',
    eyebrow: 'Meet real demand',
    description: 'Find relevant search themes, intent, difficulty, and content opportunities tied to the offer.',
    outcome: 'A prioritized keyword map with intent, page type, opportunity, and recommended next step.',
    icon: 'KW',
    accent: '#06b6d4',
    fields: [
      text('offer', 'What offer should search support?', true, '', 'offer'),
      text('audience', 'Who is searching?', true, '', 'audience'),
      text('market', 'Target geography', true, 'Country, region, or global'),
      text('seeds', 'Known seed terms', false, 'Optional starting phrases'),
    ],
    estimate: '5–9 minutes',
    outputType: 'Keyword map',
  }),
  defineWorkflow({
    id: 'seo.content.brief',
    title: 'Create an SEO content brief',
    shortTitle: 'SEO brief',
    eyebrow: 'Plan before writing',
    description: 'Build a research-backed brief around search intent, competing pages, and differentiation.',
    outcome: 'A writer-ready brief with intent, outline, entities, evidence needs, links, and success criteria.',
    icon: 'CB',
    accent: '#0891b2',
    fields: [
      text('keyword', 'Primary keyword or query', true, 'The target search'),
      text('audience', 'Who is the reader?', true, '', 'audience'),
      text('goal', 'What should the page achieve?', true, 'Educate, compare, convert, or support'),
      text('angle', 'What can you add that competitors miss?', true, 'Original expertise, data, workflow, or proof'),
    ],
    estimate: '4–7 minutes',
    outputType: 'SEO content brief',
  }),
  defineWorkflow({
    id: 'seo.backlinks.plan',
    title: 'Build a backlink plan',
    shortTitle: 'Backlink plan',
    eyebrow: 'Earn authority',
    description: 'Identify credible link opportunities based on relevance, editorial fit, and useful assets.',
    outcome: 'A prioritized outreach plan with targets, linkable assets, angles, and quality checks.',
    icon: '↗',
    accent: '#0e7490',
    fields: [
      url('target', 'Page or domain to strengthen', true),
      text('topic', 'Core topic or category', true, 'What the page deserves authority for'),
      text('market', 'Target geography or industry', false, 'Optional focus'),
      text('assets', 'Existing linkable assets', false, 'Research, tools, guides, data, or templates'),
    ],
    estimate: '6–10 minutes',
    outputType: 'Backlink opportunity plan',
  }),

  defineWorkflow({
    id: 'campaign.launch.plan',
    title: 'Plan a product launch',
    shortTitle: 'Launch plan',
    eyebrow: 'Coordinate the moment',
    description: 'Build a sequenced launch campaign around audience, positioning, proof, channels, and readiness.',
    outcome: 'A phased launch plan with messaging, assets, owners, dates, dependencies, and KPIs.',
    icon: '🚀',
    accent: '#f97316',
    fields: [
      text('product', 'What is launching?', true, 'Product, feature, offer, or market expansion'),
      text('audience', 'Who is the launch for?', true, '', 'audience'),
      text('date', 'Target launch date or window', true, 'Date or approximate timeframe'),
      textarea('readiness', 'What is already ready?', false, 'Proof, assets, channels, list, partners, or product state'),
    ],
    estimate: '8–12 minutes',
    outputType: 'Launch plan',
  }),
  defineWorkflow({
    id: 'campaign.content.30day',
    title: 'Build a 30-day campaign',
    shortTitle: '30-day campaign',
    eyebrow: 'Create momentum',
    description: 'Coordinate a month of content and conversion activity around one business objective.',
    outcome: 'A 30-day campaign calendar with themes, assets, channels, cadence, CTAs, and KPIs.',
    icon: '30',
    accent: '#ea580c',
    fields: [
      text('objective', 'What must the campaign achieve?', true, 'A measurable business or audience outcome'),
      text('audience', 'Primary audience', true, '', 'audience'),
      text('offer', 'Offer or action to support', true, '', 'offer'),
      text('channels', 'Available channels', true, 'e.g. LinkedIn, email, YouTube, TikTok, blog'),
    ],
    estimate: '7–12 minutes',
    outputType: '30-day campaign plan',
  }),
  defineWorkflow({
    id: 'campaign.gtm.strategy',
    title: 'Create a go-to-market strategy',
    shortTitle: 'GTM strategy',
    eyebrow: 'Choose the path',
    description: 'Translate the offer and market into positioning, segments, motions, channels, and tests.',
    outcome: 'A focused GTM strategy with assumptions, priorities, experiments, and decision gates.',
    icon: 'GTM',
    accent: '#c2410c',
    fields: [
      text('offer', 'What are you taking to market?', true, '', 'offer'),
      text('market', 'Which market or segment?', true, 'Industry, company size, geography, or use case'),
      text('problem', 'What urgent problem does it solve?', true, 'Describe the buyer’s current state'),
      textarea('evidence', 'What evidence do you have?', false, 'Customer proof, interviews, pipeline, usage, or market data'),
    ],
    estimate: '8–14 minutes',
    outputType: 'GTM strategy',
  }),
  defineWorkflow({
    id: 'campaign.media.plan',
    title: 'Build a media plan',
    shortTitle: 'Media plan',
    eyebrow: 'Allocate attention',
    description: 'Choose paid, owned, and earned channels based on audience, economics, and campaign goals.',
    outcome: 'A media mix with budget ranges, flighting, targeting, creative needs, and measurement plan.',
    icon: 'MP',
    accent: '#9a3412',
    fields: [
      text('objective', 'Campaign objective', true, 'Awareness, demand, leads, pipeline, or adoption'),
      text('audience', 'Target audience', true, '', 'audience'),
      text('budget', 'Budget range', true, 'Monthly or total campaign budget'),
      text('markets', 'Markets and dates', true, 'Geography and campaign window'),
    ],
    estimate: '7–12 minutes',
    outputType: 'Media plan',
  }),

  defineWorkflow({
    id: 'ads.google.search',
    title: 'Create Google Search ads',
    shortTitle: 'Google ads',
    eyebrow: 'Capture demand',
    description: 'Build intent-aligned search ads, keyword groups, negatives, and landing-page guidance.',
    outcome: 'A Google Search campaign draft with ad groups, assets, keywords, negatives, and test plan.',
    icon: 'G',
    accent: '#4285f4',
    fields: [
      text('offer', 'What are you advertising?', true, '', 'offer'),
      text('audience', 'Who is searching?', true, '', 'audience'),
      text('market', 'Target location', true, 'Country, region, or city'),
      url('landingPage', 'Landing page URL', true),
    ],
    estimate: '5–9 minutes',
    outputType: 'Google Ads package',
  }),
  defineWorkflow({
    id: 'ads.linkedin',
    title: 'Create LinkedIn ads',
    shortTitle: 'LinkedIn ads',
    eyebrow: 'Reach the buying team',
    description: 'Develop B2B ad angles, copy, creative briefs, targeting, and a structured test matrix.',
    outcome: 'A LinkedIn campaign draft with targeting, copy variants, creative briefs, and KPI assumptions.',
    icon: 'in',
    accent: '#0a66c2',
    fields: [
      text('offer', 'What are you promoting?', true, '', 'offer'),
      text('audience', 'Which roles and companies?', true, 'Titles, functions, industries, and company size'),
      text('proof', 'What proof can the ad use?', true, 'Verified result, capability, demonstration, or authority'),
      select('objective', 'Campaign objective', ['Lead generation', 'Website conversions', 'Video views', 'Brand awareness']),
    ],
    estimate: '5–9 minutes',
    outputType: 'LinkedIn Ads package',
  }),
  defineWorkflow({
    id: 'ads.meta',
    title: 'Create Meta ads',
    shortTitle: 'Meta ads',
    eyebrow: 'Test creative angles',
    description: 'Build benefit-led Meta ad concepts with hooks, copy, visual direction, and audience hypotheses.',
    outcome: 'A Meta campaign draft with copy variants, creative concepts, audiences, and test structure.',
    icon: 'M',
    accent: '#0668e1',
    fields: [
      text('offer', 'What are you promoting?', true, '', 'offer'),
      text('audience', 'Who should act?', true, '', 'audience'),
      text('benefit', 'What outcome matters most?', true, 'Specific benefit or avoided pain'),
      select('format', 'Primary format', ['Static image', 'Short video', 'Carousel', 'Mixed']),
    ],
    estimate: '5–9 minutes',
    outputType: 'Meta Ads package',
  }),
  defineWorkflow({
    id: 'ads.tiktok',
    title: 'Create TikTok ads',
    shortTitle: 'TikTok ads',
    eyebrow: 'Make the offer native',
    description: 'Create vertical ad concepts with fast hooks, clear demonstrations, and platform-native pacing.',
    outcome: 'A TikTok ad test pack with scripts, shot lists, captions, CTAs, and creative variants.',
    icon: '♪',
    accent: '#25f4ee',
    fields: [
      text('offer', 'What are you promoting?', true, '', 'offer'),
      text('audience', 'Who should care?', true, '', 'audience'),
      text('proof', 'What can we demonstrate?', true, 'Product behavior, before/after, workflow, or verified fact'),
      select('style', 'Creative style', ['Product demo', 'Problem/solution', 'Founder-style voiceover', 'Animated explainer']),
    ],
    estimate: '6–10 minutes',
    outputType: 'TikTok Ads package',
  }),

  defineWorkflow({
    id: 'code.landing.page',
    title: 'Build a campaign landing page',
    shortTitle: 'Landing-page build',
    eyebrow: 'Turn copy into code',
    description: 'Create a responsive landing-page implementation from an approved offer and conversion goal.',
    outcome: 'A tested landing-page implementation plan or code artifact with responsive and analytics checks.',
    icon: '</>',
    accent: '#60a5fa',
    fields: [
      text('offer', 'What is the page offering?', true, '', 'offer'),
      text('audience', 'Who is it for?', true, '', 'audience'),
      text('cta', 'Primary conversion action', true, 'Form, booking, purchase, signup, or download'),
      text('stack', 'Target stack or repository', true, 'e.g. React/Vite, Next.js, or WordPress'),
    ],
    estimate: '8–20 minutes',
    outputType: 'Landing-page implementation',
  }),
  defineWorkflow({
    id: 'code.marketing.calculator',
    title: 'Build a marketing calculator',
    shortTitle: 'Marketing calculator',
    eyebrow: 'Create a useful tool',
    description: 'Design an interactive calculator that makes a buyer problem concrete and captures demand.',
    outcome: 'A calculator specification and tested implementation artifact with formulas and validation.',
    icon: 'ƒx',
    accent: '#3b82f6',
    fields: [
      text('decision', 'What decision should the calculator help with?', true, 'ROI, cost, capacity, savings, or risk'),
      textarea('inputs', 'Required inputs and formulas', true, 'List known variables, units, and calculation logic'),
      text('audience', 'Who will use it?', true, '', 'audience'),
      text('stack', 'Target stack or repository', true, 'Where the calculator should live'),
    ],
    estimate: '10–25 minutes',
    outputType: 'Interactive calculator',
  }),
  defineWorkflow({
    id: 'code.tracking.audit',
    title: 'Audit marketing tracking',
    shortTitle: 'Tracking audit',
    eyebrow: 'Trust the numbers',
    description: 'Review analytics and conversion instrumentation for missing, duplicated, or misleading events.',
    outcome: 'A technical tracking audit with macro/micro event map, defects, fixes, and verification steps.',
    icon: 'GA',
    accent: '#2563eb',
    fields: [
      url('target', 'Website or application URL', true),
      text('stack', 'Analytics and tag stack', true, 'e.g. GA4, GTM, Meta Pixel, server events'),
      text('conversions', 'True business conversions', true, 'Only confirmed outcomes, not clicks or starts'),
      textarea('issues', 'Known symptoms', false, 'Missing events, duplicates, wrong attribution, or unclear definitions'),
    ],
    estimate: '8–16 minutes',
    outputType: 'Tracking audit',
  }),

  defineWorkflow({
    id: 'data.kpi.dashboard',
    title: 'Design a marketing KPI dashboard',
    shortTitle: 'KPI dashboard',
    eyebrow: 'See what matters',
    description: 'Define a decision-ready dashboard around business outcomes rather than vanity metrics.',
    outcome: 'A KPI model with definitions, data sources, formulas, layout, and alert thresholds.',
    icon: '▥',
    accent: '#14b8a6',
    fields: [
      text('objective', 'What decisions should the dashboard support?', true, 'Budget, pipeline, conversion, retention, or content'),
      textarea('sources', 'Available data sources', true, 'Analytics, CRM, ads, billing, spreadsheets, or product data'),
      text('cadence', 'Reporting cadence', true, 'Daily, weekly, monthly, or real-time'),
      text('owners', 'Who will use it?', true, 'Roles and decisions they own'),
    ],
    estimate: '6–12 minutes',
    outputType: 'KPI dashboard specification',
  }),
  defineWorkflow({
    id: 'data.channel.analysis',
    title: 'Analyze channel performance',
    shortTitle: 'Channel analysis',
    eyebrow: 'Find the signal',
    description: 'Compare channels using normalized costs, conversions, quality, and trend direction.',
    outcome: 'A channel performance analysis with comparable periods, confidence, causes, and actions.',
    icon: '↕',
    accent: '#0d9488',
    fields: [
      textarea('data', 'Provide the data or source locations', true, 'Paste a table, file URL, dashboard export, or source list'),
      text('period', 'Comparison periods', true, 'e.g. Last 7 days vs prior 7 days'),
      text('conversions', 'Which outcomes count as conversions?', true, 'Define confirmed business outcomes'),
      text('question', 'What decision are you trying to make?', true, 'Budget, channel mix, creative, or targeting'),
    ],
    estimate: '6–12 minutes',
    outputType: 'Channel analysis',
  }),
  defineWorkflow({
    id: 'data.abtest.analysis',
    title: 'Analyze an A/B test',
    shortTitle: 'A/B test analysis',
    eyebrow: 'Choose with evidence',
    description: 'Evaluate lift, uncertainty, sample quality, and whether the test supports a decision.',
    outcome: 'A test readout with effect size, confidence, caveats, and recommended action.',
    icon: 'A/B',
    accent: '#0f766e',
    fields: [
      textarea('data', 'Test data', true, 'Visitors, conversions, revenue, dates, and variant definitions'),
      text('metric', 'Primary success metric', true, 'The one metric chosen before reading results'),
      text('hypothesis', 'Original hypothesis', true, 'What change was expected and why'),
      text('segments', 'Important segments', false, 'Optional device, source, geography, or customer type'),
    ],
    estimate: '4–8 minutes',
    outputType: 'A/B test readout',
  }),
  defineWorkflow({
    id: 'data.attribution.report',
    title: 'Create an attribution report',
    shortTitle: 'Attribution report',
    eyebrow: 'Understand contribution',
    description: 'Reconcile channel touchpoints with pipeline and revenue while making uncertainty explicit.',
    outcome: 'An attribution report with model assumptions, channel contribution, gaps, and better measurement steps.',
    icon: 'Σ',
    accent: '#115e59',
    fields: [
      textarea('sources', 'Which data sources are available?', true, 'CRM, analytics, ad platforms, billing, and offline sources'),
      text('conversion', 'Confirmed conversion outcome', true, 'Lead, opportunity, sale, activation, or renewal'),
      text('window', 'Attribution window', true, 'e.g. 30-day click / 7-day view'),
      select('model', 'Preferred model', ['Compare multiple models', 'First touch', 'Last touch', 'Linear', 'Position based']),
    ],
    estimate: '8–14 minutes',
    outputType: 'Attribution report',
  }),

  defineWorkflow({
    id: 'leads.icp.define',
    title: 'Define an ideal customer profile',
    shortTitle: 'ICP definition',
    eyebrow: 'Focus the market',
    description: 'Turn evidence and constraints into a specific, testable ideal customer profile.',
    outcome: 'An ICP with firmographics, triggers, pains, buying roles, exclusions, and validation plan.',
    icon: 'ICP',
    accent: '#84cc16',
    fields: [
      text('offer', 'What are you selling?', true, '', 'offer'),
      textarea('evidence', 'What customer evidence exists?', true, 'Current clients, wins, losses, usage, interviews, or pipeline'),
      text('economics', 'Important deal economics', false, 'Price, ACV, sales cycle, delivery constraints'),
      text('exclusions', 'Who is not a fit?', false, 'Segments that waste time or cannot succeed'),
    ],
    estimate: '5–9 minutes',
    outputType: 'ICP document',
  }),
  defineWorkflow({
    id: 'leads.prospect.list',
    title: 'Build a prospect list',
    shortTitle: 'Prospect list',
    eyebrow: 'Find the right accounts',
    description: 'Identify prospects that match explicit fit and timing criteria rather than generic relevance.',
    outcome: 'A verified prospect list with fit rationale, trigger evidence, contacts, and source links.',
    icon: '◎',
    accent: '#65a30d',
    fields: [
      text('criteria', 'Ideal account criteria', true, 'Industry, size, geography, technology, and exclusions'),
      text('signal', 'Required buying or timing signal', true, 'Hiring, funding, project, recommendation request, or operational pain'),
      text('count', 'How many prospects?', true, 'e.g. 25 qualified accounts'),
      text('roles', 'Target roles', true, 'Decision-makers, champions, or users'),
    ],
    estimate: '8–15 minutes',
    outputType: 'Qualified prospect list',
  }),
  defineWorkflow({
    id: 'leads.account.research',
    title: 'Research a target account',
    shortTitle: 'Account research',
    eyebrow: 'Earn the conversation',
    description: 'Build a concise account brief from public evidence, priorities, triggers, and likely needs.',
    outcome: 'An account brief with verified facts, stakeholders, hypotheses, risks, and outreach angles.',
    icon: '⌕',
    accent: '#4d7c0f',
    fields: [
      text('company', 'Target company', true, 'Name and domain'),
      text('goal', 'Why are you researching it?', true, 'Sale, partnership, meeting, expansion, or renewal'),
      text('roles', 'Relevant people or roles', false, 'Optional names or functions'),
      textarea('context', 'What do you already know?', false, 'Relationship history, opportunity, or open questions'),
    ],
    estimate: '5–10 minutes',
    outputType: 'Account brief',
  }),
  defineWorkflow({
    id: 'leads.outreach.sequence',
    title: 'Create an outreach sequence',
    shortTitle: 'Outreach sequence',
    eyebrow: 'Start relevant conversations',
    description: 'Build a respectful, evidence-led outreach sequence around a real account trigger and useful offer.',
    outcome: 'A multi-touch sequence with personalization rules, email drafts, social touches, and stop conditions.',
    icon: '→',
    accent: '#3f6212',
    integrations: [platformIntegration('gmail', 'Gmail'), platformIntegration('linkedin', 'LinkedIn')],
    fields: [
      text('audience', 'Who are you contacting?', true, '', 'audience'),
      text('trigger', 'What makes outreach relevant now?', true, 'Specific public signal or known operational need'),
      text('offer', 'What useful help can you offer?', true, '', 'offer'),
      select('length', 'Sequence length', ['3 touches', '5 touches', '7 touches']),
    ],
    estimate: '5–9 minutes',
    outputType: 'Outreach sequence',
  }),
];

if (WORKFLOW_CATALOG.length !== 50) {
  throw new Error(`Launchpad requires exactly 50 outcomes; found ${WORKFLOW_CATALOG.length}.`);
}

export function getWorkflow(workflowId) {
  return WORKFLOW_CATALOG.find((workflow) => workflow.id === workflowId) || null;
}

export function getRequiredIntegrations(workflowId) {
  return getWorkflow(workflowId)?.integrations.filter((integration) => integration.required) || [];
}
